#!/bin/bash

#
# Generated by CMAKE from @CMAKE_CURRENT_SOURCE_DIR@/InstallAll.csh.cmake
#

# Exit immediately when any command exits with non-zero exit status
set -e

# directory to put the release in
targetDirectory=@SSSDEV_INSTALL_DIR@/@BM_VERSION_STRING@

wd=`pwd`

# main system directory
mainSystemDirectory=LinuxRHEL64
# main system binary directory
mainBinaryDirectory=$targetDirectory/$mainSystemDirectory/bin
miscDirectory=$targetDirectory/misc

# Setting UMASK
umask 0002

#building the directory structure
echo "making target directory $targetDirectory"
if [ -d $targetDirectory ]; then
   rm -rf $targetDirectory
fi
mkdir -p $targetDirectory

pushd $targetDirectory
   echo "Creating system directories"
   mkdir -p $mainSystemDirectory

   # system directory aliases
   RHELVersions="53 56 57 58 510 63 64"
   RHELFlavours="AS WS"
   echo "pwd = `pwd`"
   for flavour in $RHELFlavours
   do 
      for version in $RHELVersions
      do
         ln -s $mainSystemDirectory "LinuxRHEL64_${version}${flavour}"
      done
   done
   ln -s $mainSystemDirectory Linux
popd

# Install results of main build
install -d $targetDirectory/$mainSystemDirectory/bin
install @CMAKE_INSTALL_PREFIX@/bin/* $targetDirectory/$mainSystemDirectory/bin

# Install Geocase
cp -r @CMAKE_INSTALL_PREFIX@/misc $targetDirectory

# installing 3rdparty stuff
echo "Installing 3rdparty stuff"
echo "Installing geocosm"

tar xf @CMAKE_CURRENT_SOURCE_DIR@/../3rdparty/geocosm.tar -C $miscDirectory
pushd $miscDirectory
   echo "Installing geocosm 3rd party stuff"
   pushd geocosm/3rdparty
      echo "unpacking Xerces archive"
      tar xf Xerces.tar
      echo "unpacking xsd archive"
      tar xf xsd.tar
      echo "Installing Matlab runtime"
      echo "-P installLocation=`pwd`/matlabmcr/matlab" > MCRInstaller.in
      ./MCRInstaller.bin -silent -options MCRInstaller.in
   popd
popd

touch $miscDirectory/successfully_installed

echo "Changing group to g_psaz00"
chgrp -R g_psaz00 $targetDirectory
echo "changing mode to g+w"
chmod -R g+w $targetDirectory

