#!/bin/csh

set echo # DEBUG

#
# Generated by CMAKE from @CMAKE_CURRENT_SOURCE_DIR@/InstallAll.csh.cmake
#

# directory to put the release in
set targetDirectory=@SSSDEV_INSTALL_DIR@/@BM_VERSION_STRING@

set wd = `pwd`
set installStatus = 0

# main system directory

set mainSystemDirectory = LinuxRHEL64
# main system binary directory

set mainBinaryDirectory=$targetDirectory/$mainSystemDirectory/bin
set miscDirectory=$targetDirectory/misc


#building the directory structure
echo "making target directory $targetDirectory"
if (-d $targetDirectory) then
   rm -rf $targetDirectory
endif
mkdir -p $targetDirectory

pushd $targetDirectory

echo "Creating system directories"
mkdir -p $mainSystemDirectory

# system directory aliases
set otherSystemDirectories = "Linux LinuxRHEL64_53AS LinuxRHEL64_53WS LinuxRHEL64_56AS LinuxRHEL64_56WS LinuxRHEL64_57AS LinuxRHEL64_57WS LinuxRHEL64_58AS LinuxRHEL64_58WS"
echo "pwd = `pwd`"
foreach otherSystemDirectory ($otherSystemDirectories)
   ln -s $mainSystemDirectory $otherSystemDirectory
end
popd

cp -rp @CMAKE_INSTALL_PREFIX@/bin $targetDirectory/$mainSystemDirectory
cp -rp @CMAKE_INSTALL_PREFIX@/geocase64 $targetDirectory/$mainSystemDirectory
cp -rp @CMAKE_INSTALL_PREFIX@/misc $targetDirectory

# installing 3rdparty stuff
echo "Installing 3rdparty stuff"
echo "Installing geocosm"

tar xf @CMAKE_CURRENT_SOURCE_DIR@/../3rdparty/geocosm.tar -C $miscDirectory
pushd $miscDirectory
echo "Installing geocosm 3rd party stuff"
pushd geocosm/3rdparty
echo "unpacking Xerces archive"
tar xf Xerces.tar
echo "unpacking xsd archive"
tar xf xsd.tar
echo "Installing Matlab runtime"
echo "-P installLocation=`pwd`/matlabmcr/matlab" > MCRInstaller.in
./MCRInstaller.bin -silent -options MCRInstaller.in

popd
popd

echo "Changing group to g_psaz00"
chgrp -R g_psaz00 $targetDirectory
echo "changing mode to g+w"
chmod -R g+w $targetDirectory
