#!/bin/bash
#
# Generated by CMAKE from @CMAKE_CURRENT_SOURCE_DIR@/MoveInstalls.sh.cmake
#

# Exit immediately when a command exits with non-zero access
set -e

# Parse command line parameter
version=@BM_VERSION_STRING@
if [ "x$1" != x ]; then
   version="$1"
fi
installDirectory=@BM_SSSDEV_INSTALL_DIR@
installsToMove="${version}_b ${version}_a ${version}"
installToRemove="${version}_c"
installToMoveTo=$installToRemove

# Setting UMASK
umask 0002

# Remove the _c directory
if [ -d $installDirectory/$installToRemove ]; then
   echo "$installDirectory/$installToRemove exists, removing it"
   rm -rf $installDirectory/$installToRemove
   echo
fi

# Move  _a to _b and _b to _c
for installToMove in $installsToMove
do
   if [ -d $installDirectory/$installToMove ]; then
      echo "$installDirectory/$installToMove exists"
      if [ ! -d  $installDirectory/$installToMoveTo ]; then
	 echo "$installDirectory/$installToMoveTo does not exist"
	 echo "moving $installDirectory/$installToMove to $installDirectory/$installToMoveTo"
	 mv $installDirectory/$installToMove $installDirectory/$installToMoveTo
      else
	 echo "$installDirectory/$installToMoveTo exists"
	 echo "Cannot move $installDirectory/$installToMove to $installDirectory/$installToMoveTo"
	 exit 1
      fi
   else
      echo "$installDirectory/$installToMove does not exist"
      echo "Nothing to move"
   fi
   installToMoveTo=$installToMove
   echo
done
