#ifndef _MULTI_ARRAY_CMSTRIDEDSTEPPEDFORWARDCURSOR_H_
#define _MULTI_ARRAY_CMSTRIDEDSTEPPEDFORWARDCURSOR_H_

#define CMSTRIDEDSTEPPEDFORWARDCURSOR CMStridedSteppedForwardCursor
#define CONST
#define CONTIGUOUSSTEPPEDFORWARDCURSOR ContiguousSteppedForwardCursor
#include "multi_array/CMSTRIDEDSTEPPEDFORWARDCURSOR_CONST.h"
#undef CONST
#undef CONTIGUOUSSTEPPEDFORWARDCURSOR
#undef CMSTRIDEDSTEPPEDFORWARDCURSOR

#endif
