#ifndef _MULTI_ARRAY_CMSTRIDEDSTEPPEDCONSTCURSOR_H_
#define _MULTI_ARRAY_CMSTRIDEDSTEPPEDCONSTCURSOR_H_

#define CMSTRIDEDSTEPPEDCURSOR CMStridedSteppedConstCursor
#define CONST const
#define CONTIGUOUSSTEPPEDCURSOR ContiguousSteppedConstCursor
#include "multi_array/CMSTRIDEDSTEPPEDCURSOR_CONST.h"
#undef CONST
#undef CONTIGUOUSSTEPPEDCURSOR
#undef CMSTRIDEDSTEPPEDCURSOR

#endif
