#ifndef _MULTI_ARRAY_CMSTRIDEDSTEPPEDCONSTFORWARDCURSOR_H_
#define _MULTI_ARRAY_CMSTRIDEDSTEPPEDCONSTFORWARDCURSOR_H_

#define CMSTRIDEDSTEPPEDFORWARDCURSOR CMStridedSteppedConstForwardCursor
#define CONST const
#define CONTIGUOUSSTEPPEDFORWARDCURSOR ContiguousSteppedConstForwardCursor
#include "multi_array/CMSTRIDEDSTEPPEDFORWARDCURSOR_CONST.h"
#undef CONST
#undef CONTIGUOUSSTEPPEDFORWARDCURSOR
#undef CMSTRIDEDSTEPPEDFORWARDCURSOR

#endif
