#ifndef _MULTI_ARRAY_CONTIGUOUSSTEPPEDCONSTCURSOR_H_
#define _MULTI_ARRAY_CONTIGUOUSSTEPPEDCONSTCURSOR_H_

#define CONTIGUOUSSTEPPEDCURSOR ContiguousSteppedConstCursor
#define CONST const
#include "multi_array/CONTIGUOUSSTEPPEDCURSOR_CONST.h"
#undef CONST
#undef CONTIGUOUSSTEPPEDCURSOR

#endif
