#ifndef _MULTI_ARRAY_CONTIGUOUSSTEPPEDCONSTFORWARDCURSOR_H_
#define _MULTI_ARRAY_CONTIGUOUSSTEPPEDCONSTFORWARDCURSOR_H_

#define CONTIGUOUSSTEPPEDFORWARDCURSOR ContiguousSteppedConstForwardCursor
#define CONST const
#include "multi_array/CONTIGUOUSSTEPPEDFORWARDCURSOR_CONST.h"
#undef CONST
#undef CONTIGUOUSSTEPPEDFORWARDCURSOR

#endif
