#ifndef _MULTI_ARRAY_CONTIGUOUSSTEPPEDCURSOR_H_
#define _MULTI_ARRAY_CONTIGUOUSSTEPPEDCURSOR_H_

#define CONTIGUOUSSTEPPEDCURSOR ContiguousSteppedCursor
#define CONST 
#include "multi_array/CONTIGUOUSSTEPPEDCURSOR_CONST.h"
#undef CONST
#undef CONTIGUOUSSTEPPEDCURSOR

#endif
