#ifndef _MULTI_ARRAY_RMSTRIDEDSTEPPEDFORWARDCURSOR_H_
#define _MULTI_ARRAY_RMSTRIDEDSTEPPEDFORWARDCURSOR_H_

#include "multi_array/ContiguousSteppedForwardCursor.h"

#define RMSTRIDEDSTEPPEDFORWARDCURSOR RMStridedSteppedForwardCursor
#define CONST
#define CONTIGUOUSSTEPPEDFORWARDCURSOR ContiguousSteppedForwardCursor
#include "multi_array/RMSTRIDEDSTEPPEDFORWARDCURSOR_CONST.h"
#undef CONST
#undef CONTIGUOUSSTEPPEDFORWARDCURSOR
#undef RMSTRIDEDSTEPPEDFORWARDCURSOR

#endif
