ROOTDIR = ..
LIBDIR = ../../../libraries


FILE_BASE = ../../../files
include $(FILE_BASE)/Make.targets
include $(FILE_BASE)/Make.3rdparty
include $(FILE_BASE)/Make.libraries
include $(FILE_BASE)/Make.machine

SRCDIR  = ${ROOTDIR}/src/
CURDIR = $(cwd)

PREFDIRECOBJECTS = PreferredDirectionUnitTest.o

TAR = /apps/oss/bin/tar
MAKEDEPEND = /usr/bin/X11/makedepend

PREFDIREC = preferreddirec


INCLUDEDIRS = -I$(FINITE_ELEMENTS_INC) -I$(UTILITIES_INC)

LIB = $(FINITE_ELEMENTS_LIB) \
      $(UTILITIES_LIB) \
      -lz -lm

SELECTEDLIB = $(LIB)

vpath %.h ${SRCDIR}
vpath %.C ${SRCDIR}

OBJDIR		= .
vpath %.o ${OBJDIR}

target: $(PREFDIREC)

CFLAGS = $(DEBUGFLAGS) $(INCLUDEDIRS)

$(PREFDIREC) : $(PREFDIRECOBJECTS) $(SELECTEDLIB) Makefile
	$(LCC) $(CFLAGS) $(PREFDIRECOBJECTS) $(SELECTEDLIB) -o $(PREFDIREC)

clean:
	rm -rf $(PREFDIREC) $(PREFDIRECOBJECTS) \
	core test test.out snap.* ii_files SunWS_cache

DATE = `date +'%y%m%d_%H%M%S'`

release:
	cd ../src && $(TAR) cvhf ../releases/$(DATE).tar *.C *.h Makefile Make.*

depend: $(PREFDIRECOBJECTS:.o=.C)
	cd ../src && $(MAKEDEPEND) -f ../Makefile.cauldron2eclipse -Y $(INCLUDEDIRS) $(PREFDIRECOBJECTS:.o=.C) 2> /dev/null

# DO NOT DELETE
