#!/bin/bash
##############################################################################
# run cauldron_test compiled with -DFT_DEBUG on cauldron project, run same fission track prototype with temperature for specified sample 
# example: ./calibrationTest calibration
#################################
#run old code and prepare input for unit test
################################
./cauldron_test ${1}.project1d > ${1}OldCode.out
./prepareUnitTestInput ${1} > ${1}UnitTest.in 
#################################
#extract results from output file (old code)
################################
awk 'BEGIN{OUTPUT_RESULTS=0}{if($1=="StartOutputResults"){ OUTPUT_RESULTS=1;} else if ($1=="EndOutputResults"){ OUTPUT_RESULTS=0;} else if (OUTPUT_RESULTS){print $0;}}' ${1}OldCode.out > ${1}ResultOld.txt
#################################
#run unit test (new code)
################################
./testFissionTracks_test < ${1}UnitTest.in > ${1}ResultNew.txt
#################################
#compare results
################################
diff ${1}ResultNew.txt ${1}ResultOld.txt
