function RemoteVizRenderArea(f,q,x){function v(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(d){var b=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==d?b:b&7|8).toString(16)})}this.version=1;this.id=f;this.img=new Image;this.source;this.canvas=document.getElementById(this.id);this.ctx;this.serverHeight=this.serverWidth=0;this.canvas.width=q;this.canvas.height=x;var h=!1,m=!1;document.getElementById(f).ondragstart=function(){return!1};this.events=
{};this.addServiceListener=function(a){this.events.hasOwnProperty("ServiceEvent")?this.events.ServiceEvent.push(a):this.events.ServiceEvent=[a]};this.removeServiceListener=function(a){this.events.hasOwnProperty("ServiceEvent")&&(a=this.events.ServiceEvent.indexOf(a),-1!=a&&this.events.ServiceEvent.splice(a,1))};this.addReceivedImageListener=function(a){this.events.hasOwnProperty("ReceivedImageEvent")?this.events.ReceivedImageEvent.push(a):this.events.ReceivedImageEvent=[a]};this.removeReceivedImageListener=
function(a){this.events.hasOwnProperty("ReceivedImageEvent")&&(a=this.events.ReceivedImageEvent.indexOf(a),-1!=a&&this.events.ReceivedImageEvent.splice(a,1))};this.addResizeListener=function(a){this.events.hasOwnProperty("ResizeEvent")?this.events.ResizeEvent.push(a):this.events.ResizeEvent=[a]};this.removeResizeListener=function(a){this.events.hasOwnProperty("ResizeEvent")&&(a=this.events.ResizeEvent.indexOf(a),-1!=a&&this.events.ResizeEvent.splice(a,1))};this.addMessageListener=function(a){this.events.hasOwnProperty("CommandEvent")?
this.events.CommandEvent.push(a):this.events.CommandEvent=[a]};this.removeMessageListener=function(a){this.events.hasOwnProperty("CommandEvent")&&(a=this.events.CommandEvent.indexOf(a),-1!=a&&this.events.CommandEvent.splice(a,1))};this.addMouseMoveListener=function(a){this.events.hasOwnProperty("MouseMoveEvent")?this.events.MouseMoveEvent.push(a):this.events.MouseMoveEvent=[a]};this.removeMouseMoveListener=function(a){this.events.hasOwnProperty("MouseMoveEvent")&&(a=this.events.MouseMoveEvent.indexOf(a),
-1!=a&&this.events.MouseMoveEvent.splice(a,1))};this.addMouseDownListener=function(a){this.events.hasOwnProperty("MouseDownEvent")?this.events.MouseDownEvent.push(a):this.events.MouseDownEvent=[a]};this.removeMouseDownListener=function(a){this.events.hasOwnProperty("MouseDownEvent")&&(a=this.events.MouseDownEvent.indexOf(a),-1!=a&&this.events.MouseDownEvent.splice(a,1))};this.addMouseUpListener=function(a){this.events.hasOwnProperty("MouseUpEvent")?this.events.MouseUpEvent.push(a):this.events.MouseUpEvent=
[a]};this.removeMouseUpListener=function(a){this.events.hasOwnProperty("MouseUpEvent")&&(a=this.events.MouseUpEvent.indexOf(a),-1!=a&&this.events.MouseUpEvent.splice(a,1))};this.addMouseOverListener=function(a){this.events.hasOwnProperty("MouseOverEvent")?this.events.MouseOverEvent.push(a):this.events.MouseOverEvent=[a]};this.removeMouseOverListener=function(a){this.events.hasOwnProperty("MouseOverEvent")&&(a=this.events.MouseOverEvent.indexOf(a),-1!=a&&this.events.MouseOverEvent.splice(a,1))};this.addMouseOutListener=
function(a){this.events.hasOwnProperty("MouseOutEvent")?this.events.MouseOutEvent.push(a):this.events.MouseOutEvent=[a]};this.removeMouseOutListener=function(a){this.events.hasOwnProperty("MouseOutEvent")&&(a=this.events.MouseOutEvent.indexOf(a),-1!=a&&this.events.MouseOutEvent.splice(a,1))};this.addMouseWheelListener=function(a){this.events.hasOwnProperty("MouseWheelEvent")?this.events.MouseWheelEvent.push(a):this.events.MouseWheelEvent=[a]};this.removeMouseWheelListener=function(a){this.events.hasOwnProperty("MouseWheelEvent")&&
(a=this.events.MouseWheelEvent.indexOf(a),-1!=a&&this.events.MouseWheelEvent.splice(a,1))};this.addTouchStartListener=function(a){this.events.hasOwnProperty("TouchStartEvent")?this.events.TouchStartEvent.push(a):this.events.TouchStartEvent=[a]};this.removeTouchStartListener=function(a){this.events.hasOwnProperty("TouchStartEvent")&&(a=this.events.TouchStartEvent.indexOf(a),-1!=a&&this.events.TouchStartEvent.splice(a,1))};this.addTouchEndListener=function(a){this.events.hasOwnProperty("TouchEndEvent")?
this.events.TouchEndEvent.push(a):this.events.TouchEndEvent=[a]};this.removeTouchEndListener=function(a){this.events.hasOwnProperty("TouchEndEvent")&&(a=this.events.TouchEndEvent.indexOf(a),-1!=a&&this.events.TouchEndEvent.splice(a,1))};this.addTouchCancelListener=function(a){this.events.hasOwnProperty("TouchCancelEvent")?this.events.TouchCancelEvent.push(a):this.events.TouchCancelEvent=[a]};this.removeTouchCancelListener=function(a){this.events.hasOwnProperty("TouchCancelEvent")&&(a=this.events.TouchCancelEvent.indexOf(a),
-1!=a&&this.events.TouchCancelEvent.splice(a,1))};this.addTouchMoveListener=function(a){this.events.hasOwnProperty("TouchMoveEvent")?this.events.TouchMoveEvent.push(a):this.events.TouchMoveEvent=[a]};this.removeTouchMoveListener=function(a){this.events.hasOwnProperty("TouchMoveEvent")&&(a=this.events.TouchMoveEvent.indexOf(a),-1!=a&&this.events.TouchMoveEvent.splice(a,1))};this.addKeyUpListener=function(a){this.events.hasOwnProperty("KeyUpEvent")?this.events.KeyUpEvent.push(a):this.events.KeyUpEvent=
[a]};this.removeKeyUpListener=function(a){this.events.hasOwnProperty("KeyUpEvent")&&(a=this.events.KeyUpEvent.indexOf(a),-1!=a&&this.events.KeyUpEvent.splice(a,1))};this.addKeyDownListener=function(a){this.events.hasOwnProperty("KeyDownEvent")?this.events.KeyDownEvent.push(a):this.events.KeyDownEvent=[a]};this.removeKeyDownListener=function(a){this.events.hasOwnProperty("KeyDownEvent")&&(a=this.events.KeyDownEvent.indexOf(a),-1!=a&&this.events.KeyDownEvent.splice(a,1))};var c=function(a,d,b){if(!a.events.hasOwnProperty(b))return!0;
a=a.events[b];b=a.length;for(var r=!1,c=0;c<b;c++)r|=a[c](d);return r},y=function(a,d){if(a.events.hasOwnProperty("ReceivedImageEvent")){d&&d.length||(d=[]);for(var b=a.events.ReceivedImageEvent,c=b.length,e=0;e<c;e++)b[e].apply(null,d)}},s=function(a,d){if(a.events.hasOwnProperty("ServiceEvent")){d&&d.length||(d=[]);for(var b=a.events.ServiceEvent,c=b.length,e=0;e<c;e++)b[e].apply(null,d)}};!window.WebSocket&&window.MozWebSocket?window.WebSocket=window.MozWebSocket:window.WebSocket||window.MozWebSocket||
alert("Your browser does not support WebSocket.");var e=function(a,d){return function(){return d.apply(a,arguments)}};this.sendMessage=function(a){if(h&&null!=this.websocket){var d={type:"command"};d.message=a;this.websocket.send(JSON.stringify(d))}};this.requestRenderAreaSize=function(a,d){if(h&&null!=this.websocket){var b={type:"requestsize"};b.width=parseInt(a);b.height=parseInt(d);this.websocket.send(JSON.stringify(b))}};this.getContainerWidth=function(){return this.canvas.width};this.getContainerHeight=
function(){return this.canvas.height};this.getRenderAreaWidth=function(){return this.serverWidth};this.getRenderAreaHeight=function(){return this.serverHeight};this.resizeRenderAreaContainer=function(a,d){this.canvas.width=a;this.canvas.height=d;this.ctx.clearRect(0,0,this.ctx.canvas.width,this.ctx.canvas.height);this.redraw();if(h&&null!=this.websocket){var b={type:"resizecontainer"};b.width=parseInt(a);b.height=parseInt(d);this.websocket.send(JSON.stringify(b))}};var t=function(a){for(var d=a.offsetLeft,
b=a.offsetTop;a=a.offsetParent;)d+=a.offsetLeft-a.scrollLeft,b+=a.offsetTop-a.scrollTop;return{left:d,top:b}},n=function(a,d,b){"mousedown"==d?m=!0:"mouseup"==d&&(m=!1);var c=t(a.canvas),e=(b.clientX-c.left+window.pageXOffset)*a.serverWidth/a.canvas.width,c=(a.canvas.height-(b.clientY-c.top+window.pageYOffset))*a.serverHeight/a.canvas.height;if(h&&null!=a.websocket){var l={type:"mouseevent"};l.event=d;l.x=e;l.y=c;l.button=b.button;a.websocket.send(JSON.stringify(l))}},w=function(a,d,b){if(h&&null!=
a.websocket){var c={type:"keyevent"};c.event=d;c.key=b.keyCode;a.websocket.send(JSON.stringify(c))}},p=function(a,d,b){for(var c=b.changedTouches,e=0;e<c.length;e++){var l=c[e],g=t(a.canvas),k=(l.clientX-g.left+window.pageXOffset)*a.serverWidth/a.canvas.width,g=(a.canvas.height-(l.clientY-g.top+window.pageYOffset))*a.serverHeight/a.canvas.height;if(h&&null!=a.websocket){var f={type:"touchevent"};f.event=d;f.id=l.identifier;f.x=k;f.y=g;a.websocket.send(JSON.stringify(f))}}b.preventDefault()},k=function(a,
d,b){"down"==d&&a.canvas.focus();if(b.pointerType==b.MSPOINTER_TYPE_MOUSE||"mouse"==b.pointerType)"up"==d?m=!1:"down"==d&&(m=!0);var c=t(a.canvas),e=(b.clientX-c.left+window.pageXOffset)*a.serverWidth/a.canvas.width,c=(a.canvas.height-(b.clientY-c.top+window.pageYOffset))*a.serverHeight/a.canvas.height;if(h&&null!=a.websocket){var f=d;if(b.pointerType==b.MSPOINTER_TYPE_MOUSE||"mouse"==b.pointerType){var g={type:"mouseevent"};g.event="mouse"+d;g.x=e;g.y=c;g.button=0!=b.which?b.which-1:-1;a.websocket.send(JSON.stringify(g))}else if(b.pointerType==
b.MSPOINTER_TYPE_TOUCH||"touch"==b.pointerType){if("down"==d||"enter"==d)f="start";else if("up"==d||"cancel"==d||"leave"==d)f="end";g={type:"touchevent"};g.event="touch"+f;g.x=e;g.y=c;g.id=b.pointerId;a.websocket.send(JSON.stringify(g))}}b.preventDefault()},u=function(a,d){if(h&&null!=a.websocket){var b={type:"mouseevent",event:"mousewheel"};b.delta=d.wheelDelta;a.websocket.send(JSON.stringify(b))}};f=function(a){if(h){var d={type:"mouseevent",event:"mousewheel"};d.delta=120*-(a.detail/3);this.websocket.send(JSON.stringify(d))}};
"undefined"!=typeof this.canvas.style.msTouchAction&&(this.canvas.style.msTouchAction="none");"undefined"!=typeof this.canvas.style.TouchAction&&(this.canvas.style.TouchAction="none");this.ctx=this.canvas.getContext("2d");this.redraw=function(){this.ctx.drawImage(this.img,0,0,this.ctx.canvas.width,this.ctx.canvas.height)};this.img.onload=e(this,this.redraw);q=function(){var a=navigator.userAgent.toLowerCase();return-1!=a.indexOf("msie")?parseInt(a.split("msie")[1]):!1};window.navigator.msPointerEnabled||
window.navigator.pointerEnabled?10==q()?(this.canvas.onmspointerdown=e(this,function(a){(a.pointerType==a.MSPOINTER_TYPE_MOUSE&&c(this,a,"MouseDownEvent")||a.pointerType==a.MSPOINTER_TYPE_TOUCH&&c(this,a,"TouchStartEvent"))&&k(this,"down",a)}),this.canvas.onmspointermove=e(this,function(a){(a.pointerType==a.MSPOINTER_TYPE_MOUSE&&c(this,a,"MouseMoveEvent")||a.pointerType==a.MSPOINTER_TYPE_TOUCH&&c(this,a,"TouchMoveEvent"))&&k(this,"move",a)}),this.canvas.onmspointerup=e(this,function(a){(a.pointerType==
a.MSPOINTER_TYPE_MOUSE&&c(this,a,"MouseUpEvent")||a.pointerType==a.MSPOINTER_TYPE_TOUCH&&c(this,a,"TouchEndEvent"))&&k(this,"up",a)}),this.canvas.onmspointercancel=e(this,function(a){a.pointerType==a.MSPOINTER_TYPE_TOUCH&&c(this,a,"TouchCancelEvent")&&k(this,"cancel",a)}),this.canvas.onmspointerout=e(this,function(a){(a.pointerType==a.MSPOINTER_TYPE_MOUSE&&c(this,a,"MouseOutEvent")||a.pointerType==a.MSPOINTER_TYPE_TOUCH&&c(this,a,"TouchEndEvent"))&&k(this,"leave",a)}),this.canvas.onmspointerover=
e(this,function(a){(a.pointerType==a.MSPOINTER_TYPE_MOUSE&&c(this,a,"MouseOverEvent")||a.pointerType==a.MSPOINTER_TYPE_TOUCH&&c(this,a,"TouchStartEvent"))&&k(this,"enter",a)}),this.canvas.onmousewheel=e(this,function(a){c(this,a,"MouseWheelEvent")&&u(this,a)}),f=e(this,function(a){m&&a.pointerType==a.MSPOINTER_TYPE_MOUSE&&c(this,a,"MouseUpEvent")&&k(this,"up",a)}),window.addEventListener("MSPointerUp",f,!1)):(this.canvas.onpointerdown=e(this,function(a){("mouse"==a.pointerType&&c(this,a,"MouseDownEvent")||
"touch"==a.pointerType&&c(this,a,"TouchStartEvent"))&&k(this,"down",a)}),this.canvas.onpointermove=e(this,function(a){("mouse"==a.pointerType&&c(this,a,"MouseMoveEvent")||"touch"==a.pointerType&&c(this,a,"TouchMoveEvent"))&&k(this,"move",a)}),this.canvas.onpointerup=e(this,function(a){("mouse"==a.pointerType&&c(this,a,"MouseUpEvent")||"touch"==a.pointerType&&c(this,a,"TouchEndEvent"))&&k(this,"up",a)}),this.canvas.onpointercancel=e(this,function(a){"touch"==a.pointerType&&c(this,a,"TouchCancelEvent")&&
k(this,"cancel",a)}),this.canvas.onpointerout=e(this,function(a){("mouse"==a.pointerType&&c(this,a,"MouseOutEvent")||"touch"==a.pointerType&&c(this,a,"TouchEndEvent"))&&k(this,"leave",a)}),this.canvas.onpointerover=e(this,function(a){("mouse"==a.pointerType&&c(this,a,"MouseOverEvent")||"touch"==a.pointerType&&c(this,a,"TouchStartEvent"))&&k(this,"enter",a)}),this.canvas.onmousewheel=e(this,function(a){c(this,a,"MouseWheelEvent")&&u(this,a)}),f=e(this,function(a){m&&"mouse"==a.pointerType&&c(this,
a,"MouseUpEvent")&&k(this,"up",a)}),window.addEventListener("pointerup",f,!1)):(this.canvas.ontouchstart=e(this,function(a){c(this,a,"TouchStartEvent")&&p(this,"touchstart",a)}),this.canvas.ontouchmove=e(this,function(a){c(this,a,"TouchMoveEvent")&&p(this,"touchmove",a)}),this.canvas.ontouchend=e(this,function(a){c(this,a,"TouchEndEvent")&&p(this,"touchend",a)}),this.canvas.ontouchcancel=e(this,function(a){c(this,a,"TouchCancelEvent")&&p(this,"touchend",a)}),this.canvas.onmousedown=e(this,function(a){c(this,
a,"MouseDownEvent")&&n(this,"mousedown",a)}),this.canvas.onmouseover=e(this,function(a){c(this,a,"MouseOverEvent")&&n(this,"mouseenter",a)}),this.canvas.onmouseout=e(this,function(a){c(this,a,"MouseOutEvent")&&n(this,"mouseleave",a)}),this.canvas.onmouseup=e(this,function(a){c(this,a,"MouseUpEvent")&&n(this,"mouseup",a)}),this.canvas.onmousemove=e(this,function(a){c(this,a,"MouseMoveEvent")&&n(this,"mousemove",a)}),this.canvas.onmousewheel=e(this,function(a){c(this,a,"MouseWheelEvent")&&u(this,a)}),
f=f.bind(this),this.canvas.addEventListener("DOMMouseScroll",f,!1),f=e(this,function(a){m&&c(this,a,"MouseUpEvent")&&n(this,"mouseup",a)}),window.addEventListener("mouseup",f,!1));this.canvas.onkeyup=e(this,function(a){c(this,a,"KeyUpEvent")&&w(this,"keyup",a)});this.canvas.onkeydown=e(this,function(a){c(this,a,"KeyDownEvent")&&w(this,"keydown",a)});this.canvas.setAttribute("tabindex","0");this.canvas.focus();var z=function(a){h&&null!=a.websocket&&a.websocket.send(JSON.stringify({type:"alive"}))};
this.wsonopen=function(){var a;a=this.svcUrl;var d=this.canvas.width,b=this.canvas.height,c=a.match("^((ws|wss)://)([^/]*)")||[];a=0<c.length?-1==a.indexOf("requestedHeight")&&-1==a.indexOf("requestedWidth")?-1==a.indexOf("?")?a.slice(c[0].length+1,a.length)+"?requestedWidth="+d+"&requestedHeight="+b:a.slice(c[0].length+1,a.length)+"&requestedWidth="+d+"&requestedHeight="+b:a.slice(c[0].length+1,a.length):null;null!=a?("undefined"!=typeof localStorage?localStorage.getItem("RemoteViz")?d=localStorage.getItem("RemoteViz"):
(d=v(),localStorage.setItem("RemoteViz",d)):d=v(),b={type:"connection"},b.protocolversion=this.version,b.url=a,b.id=d,b.applicationname=window.location.host,b.containerwidth=this.canvas.width,b.containerheight=this.canvas.height,this.websocket.send(JSON.stringify(b))):alert("Bad URL format.")};this.wsonclose=function(a){if(h){h=!1;var c=this;setTimeout(function(){s(c,[["disconnected","NETWORKFAILURE"]])},1)}};this.wsonmessage=function(a){if(null!=this.websocket){var c=this,b=JSON.parse(a.data);"accept"==
b.type?(this.serverWidth=b.width,this.serverHeight=b.height,h=!0,setInterval(z,5E3,c),setTimeout(function(){s(c,[["connected",b.width,b.height]])},1)):h&&"command"==b.type?setTimeout(function(){var a=[b.message];if(c.events.hasOwnProperty("CommandEvent")){a&&a.length||(a=[]);for(var e=c.events.CommandEvent,f=e.length,g=0;g<f;g++)e[g].apply(null,a)}},1):h&&"resize"==b.type?(this.serverWidth=b.width,this.serverHeight=b.height,setTimeout(function(){var a=[[b.width,b.height]];if(c.events.hasOwnProperty("ResizeEvent")){a&&
a.length||(a=[]);for(var e=c.events.ResizeEvent,f=e.length,g=0;g<f;g++)e[g].apply(null,a)}},1)):"disconnect"==b.type?setTimeout(function(){s(c,[["disconnected",b.reason]])},1):h&&"image"==b.type&&(this.img.src="data:"+b.contenttype+";base64,"+b.data,y(c,[b.data.length]),this.websocket.send(JSON.stringify({type:"ack"})))}};this.connectTo=function(a){this.svcUrl=a;this.websocket=new WebSocket(a);this.websocket.onopen=e(this,this.wsonopen);this.websocket.onclose=e(this,this.wsonclose);this.websocket.onmessage=
e(this,this.wsonmessage)};this.disconnect=function(){null!=this.websocket&&(this.websocket.close(),this.websocket=null,h=!1)};this.isConnected=function(){return null!=this.websocket?1==this.websocket.readyState:!1}};
