#!/bin/bash
#
# resources_SIEP-BV - GEMPIS resource definitions for regional users
#
# Purpose: defines GEMPIS system resources. This file does not define 
# user resources which are stored in ~/.gempis/resource_user.
# 
# References: See GEMPIS User manual for details.
#
# This file is executed in a korn shell to define references.
# Lines preceeded by a '#' are treated as comments.
# Not all properties need to be defined.
# Properties with the same index value describe the same object.
#
# Format: <property>[<index>]="<value>"
#
# Only index values from 11 and 20 are permitted in the system configuration.
# Do not use spaces between '=' character.
# Make sure group definitions use different index values. 
#
# Example: res_jobtype[13]="MPICH"
#
# Properties:
# res_name      - (required) Resource name as used in the gempis command.
# res_jobtype   - (required) Job Type: STANDALONE, LSF, or LSFHPC, or CUSTOM.
# res_mpiref    - (required) MPI Reference name: refers to an entry in the 
#	gempis_MPIRef file.
# res_remote    - Name of 1 or more remote computer to submit the gempis command.
# res_request   - Identifier to use when requesting resource information. 
# res_submit    - Identifier to use when submitting a job.
# res_prepath   - Prepend directory list to PATH (separate entries using the 
#	colon character ':' as used in the PATH)
# res_cluster   - Cluster list: a list of computer names and number of 
#	processors when Job Type is CUSTOM.
###############################################################

#
#
res_name[11]="Darwin"
res_jobtype[11]="LSFHPC"
res_mpiref[11]="INTELMPI"
res_remote[11]="amsdc1-n-s00037 amsdc1-n-s00036"
res_request[11]="cldrn"
res_submit[11]="-P cldrn"
#res_prepath[11]=""
#res_cluster[11]=""

res_name[12]="AMSGDC"
res_jobtype[12]="LSFHPC"
res_mpiref[12]="INTELMPI"
res_remote[12]="amsdc1-n-s00231.europe.shell.com"
res_request[12]="cldrn"
res_submit[12]="-P cldrn -We 01:00"

#
# Undefined resource 13
#
#res_name[13]=""
#res_jobtype[13]=""
#res_mpiref[13]=""
#res_remote[13]=""
#res_request[13]=""
#res_submit[13]=""
#res_prepath[13]=""
#res_cluster[13]=""

#
# Undefined resource 14
#
#res_name[14]=""
#res_jobtype[14]=""
#res_mpiref[14]=""
#res_remote[14]=""
#res_request[14]=""
#res_submit[14]=""
#res_prepath[14]=""
#res_cluster[14]=""

#
# Undefined resource 15
#
#res_name[15]=""
#res_jobtype[15]=""
#res_mpiref[15]=""
#res_remote[15]=""
#res_request[15]=""
#res_submit[15]=""
#res_prepath[15]=""
#res_cluster[15]=""

#
# Undefined resource 16
#
#res_name[16]=""
#res_jobtype[16]=""
#res_mpiref[16]=""
#res_remote[16]=""
#res_request[16]=""
#res_submit[16]=""
#res_prepath[16]=""
#res_cluster[16]=""

#
# Undefined resource 17
#
#res_name[17]=""
#res_jobtype[17]=""
#res_mpiref[17]=""
#res_remote[17]=""
#res_request[17]=""
#res_submit[17]=""
#res_prepath[17]=""
#res_cluster[17]=""

#
# Undefined resource 18
#
#res_name[18]=""
#res_jobtype[18]=""
#res_mpiref[18]=""
#res_remote[18]=""
#res_request[18]=""
#res_submit[18]=""
#res_prepath[18]=""
#res_cluster[18]=""

#
# Undefined resource 19
#
#res_name[19]=""
#res_jobtype[19]=""
#res_mpiref[19]=""
#res_remote[19]=""
#res_request[19]=""
#res_submit[19]=""
#res_prepath[19]=""
#res_cluster[19]=""

#
# Undefined resource 20
#
#res_name[20]=""
#res_jobtype[20]=""
#res_mpiref[20]=""
#res_remote[20]=""
#res_request[20]=""
#res_submit[20]=""
#res_prepath[20]=""
#res_cluster[20]=""

echo "" >/dev/null
# End Script
