ROOTDIR	= ..
LIBDIR = ../../../libraries

FILE_BASE = ../../../files
include $(FILE_BASE)/Make.fctargets
include $(FILE_BASE)/Make.3rdparty
include $(FILE_BASE)/Make.libraries
include $(FILE_BASE)/Make.machine

CC = $(CXX)
CLINKER = $(CC)

FLEXLMBITS      = 64
FLEX_LIB        = $(FLEXLMINCLUDEDIR)/$(APPSOS)/lib$(FLEXLMBITS)/EPTFlexLm.o
FLEX_INCLUDE    = $(FLEXLMINCLUDEDIR)/include

#
#  Override for Make.machine definitions
ifeq ($(machine),Linux64)
  MP_INCLUDE	  = $(MPI_INCLUDE)
  FLEX_LIB        = $(FLEXLMINCLUDEDIR)/LinuxRHEL_i686_30WS/lib$(FLEXLMBITS)/EPTFlexLm.o  
endif
#
ifeq ($(machine),Sun)
  MP_INCLUDE	  = /opt/SUNWhpc/include/v9
  SOCKET_LIB      = -L/usr/lib/sparcv9 -lsocket -lnsl /apps/oss/lib/gcc-lib/sparc-sun-solaris2.8/2.95.3/libgcc.a
  FTNLIB	  = -lF77 -lM77 -lsunmath
endif
#
ifeq ($(machine),SunOS64)
  MP_INCLUDE      = /opt/SUNWhpc/include/v9
  SOCKET_LIB      = -L/usr/lib/sparcv9 -lsocket -lnsl /apps/oss/lib/gcc-lib/sparc-sun-solaris2.8/2.95.3/libgcc.a
  FTNLIB	  = -lF77 -lM77 -lsunmath
endif
#
ifeq ($(machine),Silicon64)
  MP_INCLUDE      = /usr/include/CC
  SOCKET_LIB      = -L/usr/lib64/mips4 -lsocket -woff 15
endif

MAKEDEPEND = /usr/bin/X11/makedepend

DOXYGEN = doxygen
DOXYGENCFG = fastcauldron.cfg

SRCDIR  	= $(ROOTDIR)/src/

CBMGENERICS_INC	= $(LIBDIR)/CBMGenerics/src
CBMGENERICS_LIB	= $(LIBDIR)/lib/$(machine)/libCBMGenerics.a

CALIBRATIONKERNEL_INC	= $(LIBDIR)/calibration_kernel/src
CALIBRATIONKERNEL_LIB	= $(LIBDIR)/lib/$(machine)/libcalibration_kernel.a


EXEOBJECTS	=    main.o 		  

EXESRCS 	= $(EXEOBJECTS:.o=.C)

EXELIBS		= $(CALIBRATIONKERNEL_LIB) \
                  $(CBMGENERICS_LIB)\
		  $(SOCKET_LIB) -lz -lrt -lm

CFLAGS		=  -I/usr/include -I$(CALIBRATIONKERNEL_INC) -I$(CBMGENERICS_INC) ${PROFILEFLAGS} ${COMPILEFLAGS} ${DEBUGFLAGS}

vpath %.h $(SRCDIR)
vpath %.C $(SRCDIR)


EXE = testFissionTracks

target: $(EXE)

$(EXE): $(EXEOBJECTS)
	-$(PRELINK) $(CLINKER) $(LDFLAGS) -o $(EXE) $(EXEOBJECTS) $(EXELIBS)

clean :
	rm -rf $(EXEOBJECTS) $(EXE) ii_files

doc:
	cd ../src && $(DOXYGEN) $(DOXYGENCFG)

depend: $(EXEOBJECTS:.o=.C)
	cd ../src && $(MAKEDEPEND) -f../Makefile.fastcauldron -Y $(INCLUDEDIRS) $(EXEOBJECTS:.o=.C) 2> /dev/null

# DO NOT DELETE

