#!/bin/sh
set -x
cd /apps/sssdev/ibs

WHOAMI=`/usr/bin/whoami`
REMOTEUSER=s_bpac00
REMOTECOMPUTER=houcy1-n-sp030b01.americas.shell.com
REMOTEACCOUNT=$REMOTEUSER@$REMOTECOMPUTER
SSHKEYFILE=${HOME}/${REMOTEUSER}-id_dsa
IBSDIRECTORY=/apps/sssdev/ibs
if [ $# -eq 0 ]
then
   VERSION=v2013.10nightly
else
   VERSION=$1
fi
IBSVERSIONDIRECTORY=${IBSDIRECTORY}/${VERSION}

ssh -q -i $SSHKEYFILE $REMOTEACCOUNT "rm -rf ${IBSVERSIONDIRECTORY}_a; mv ${IBSVERSIONDIRECTORY} ${IBSVERSIONDIRECTORY}_a"
rsync -az -e "ssh -x -q -i $SSHKEYFILE" ${IBSVERSIONDIRECTORY}/  ${REMOTEACCOUNT}:${IBSVERSIONDIRECTORY}
ssh -q -i $SSHKEYFILE $REMOTEACCOUNT "cd ${IBSVERSIONDIRECTORY}/misc/geocosm/3rdparty;/bin/rm -rf matlabmcr;echo '-P installLocation=${IBSVERSIONDIRECTORY}/misc/geocosm/3rdparty/matlabmcr/matlab' > MCRInstaller.in;./MCRInstaller.bin -silent -options MCRInstaller.in"
