#!/bin/sh
# verbose mode
set -x
# exit whenever a command returns with a non-zero exit status
set -e

# Constants
WHOAMI=`/usr/bin/whoami`
REMOTEUSER=s_bpac00
REMOTECOMPUTER=houcy1-n-sp030b01.americas.shell.com
REMOTEACCOUNT=$REMOTEUSER@$REMOTECOMPUTER
SSHKEYFILE=${HOME}/${REMOTEUSER}-id_dsa
IBSDIRECTORY=/apps/sssdev/ibs

# Version number
if [ $# -lt 1 ]; then
  echo "Usage: ReleaseToHouston VERSION"
  echo "  where VERSION is the version number of the build you want to copy"
  exit 1
else
   VERSION=$1
fi

PLATFORM=`getos2`
MAIN=${IBSDIRECTORY}/${VERSION}
BINARIES=${MAIN}/${PLATFORM}
PLATFORM_INDEPENDENT=${MAIN}/misc
RSH="ssh -x -q -i $SSHKEYFILE"

# Create destination directory
${RSH} ${REMOTEACCOUNT} mkdir -p ${MAIN}

# Copy the binaries
rsync --recursive --delete --links --perms --group --rsh="${RSH}" ${BINARIES}/  ${REMOTEACCOUNT}:${BINARIES}

# Copy the platform independent files
rsync --recursive --delete --links --perms --group --rsh="${RSH}" ${PLATFORM_INDEPENDENT}/  ${REMOTEACCOUNT}:${PLATFORM_INDEPENDENT}

# Copy files in the main group
rsync --links --perms --group --rsh="${RSH}" ${MAIN}/  ${REMOTEACCOUNT}:${MAIN}

