/// Class SourceGraphForm inherits from InteractiveGraphForm and 
/// adds functionality to show source rock origin data for one component
/// at a time. The graph adds a drop down list with the component options

#ifndef __sourceGraphForm__
#define __sourceGraphForm__

#include "interactivegraphform.h"

class QComboBox;
class SourceReader;

class SourceGraphForm : public InteractiveGraphForm
{
public:
   // public member (doing same way as in GraphForm, which is generated by QT)
   QComboBox* SelectComponentBox;

   // ctor / dtor
   SourceGraphForm (QWidget* parent = 0, const char* name = 0, WFlags fl = 0)
      : InteractiveGraphForm (parent, name, fl) 
   {
      createComboBox ();
   }

   // public methods
   char* getSelectedComponent (void) { return m_selectedComponent; }
   void setReader (DataReader *reader) { InteractiveGraphForm::setReader (reader); }
   void setReader (SourceReader *reader) { m_sourceReader = reader; }
   DataReader* getReader();
   string refreshGraph ();
   
public slots:
   virtual void componentSelectedSlot();
   
private:
   // private methods
   void createComboBox ();
   void resizeEvent (QResizeEvent *size);
   int compBoxX();
   int compBoxY();
   void resetSelectedComponent();
   void rereadData();
    
   // private variables
   char *m_selectedComponent;
   SourceReader *m_sourceReader;
};

#endif
