#ifndef _MULTI_ARRAY_CMSTRIDEDSTEPPEDCURSOR_H_
#define _MULTI_ARRAY_CMSTRIDEDSTEPPEDCURSOR_H_

#define CMSTRIDEDSTEPPEDCURSOR CMStridedSteppedCursor
#define CONTIGUOUSSTEPPEDCURSOR ContiguousSteppedCursor
#define CONST
#include "multi_array/CMSTRIDEDSTEPPEDCURSOR_CONST.h"
#undef CONST
#undef CONTIGUOUSSTEPPEDCURSOR
#undef CMSTRIDEDSTEPPEDCURSOR

#endif
