#ifndef _MULTI_ARRAY_CONTIGUOUSSTEPPEDFORWARDCURSOR_H_
#define _MULTI_ARRAY_CONTIGUOUSSTEPPEDFORWARDCURSOR_H_

#define CONTIGUOUSSTEPPEDFORWARDCURSOR ContiguousSteppedForwardCursor
#define CONST
#include "multi_array/CONTIGUOUSSTEPPEDFORWARDCURSOR_CONST.h"
#undef CONST
#undef CONTIGUOUSSTEPPEDFORWARDCURSOR

#endif
