#ifndef _MULTI_ARRAY_RMSTRIDEDSTEPPEDCONSTFORWARDCURSOR_H_
#define _MULTI_ARRAY_RMSTRIDEDSTEPPEDCONSTFORWARDCURSOR_H_

#include "multi_array/ContiguousSteppedConstForwardCursor.h"

#define RMSTRIDEDSTEPPEDFORWARDCURSOR RMStridedSteppedConstForwardCursor
#define CONST const
#define CONTIGUOUSSTEPPEDFORWARDCURSOR ContiguousSteppedConstForwardCursor
#include "multi_array/RMSTRIDEDSTEPPEDFORWARDCURSOR_CONST.h"
#undef CONST
#undef CONTIGUOUSSTEPPEDFORWARDCURSOR
#undef RMSTRIDEDSTEPPEDFORWARDCURSOR

#endif
