//
// Copyright (C) 2022 Shell International Exploration & Production.
// All rights reserved.
//
// Confidential and proprietary source code of Shell.
// Do not distribute without written permission from Shell.
//

// Class to read data results from track1d
// The wells are read in the order of sortedIndices,
// this is relevant, because the sorting based on x-value is generated by
// CASA
#pragma once

#include "caseDataCreator.h"
#include <QVector>

namespace casaWizard
{

namespace sac
{

class WellTrajectoryManager;
class WellTrajectory;

class SacScenario;

class WellTrajectoryDataCreator : public CaseDataCreator
{
public:
  WellTrajectoryDataCreator(SacScenario& scenario, const QString& projectName, const QString& iterationPath);

private:
  struct WellData
  {
    QVector<double> depth;
    QVector<double> value;
  };

  void readCase(const int wellIndex, const int caseIndex);
  WellData readSingleTrajectory(const WellTrajectory& trajectory, const QString& dataFolder, const QString& projectName);

  WellTrajectoryManager& m_wellTrajectoryManager;
  QString m_projectName;
};

} // namespace sac

} // namespace casaWizard
