ROOTDIR = ..
LIBDIR = ../../../libraries


FILE_BASE = ../../../files
include $(FILE_BASE)/Make.targets
include $(FILE_BASE)/Make.hdf5

SRCDIR  = ${ROOTDIR}/src/
CURDIR = $(cwd)

MLOBJECTS = \
	ProjectHandle.o \
	PersistentTrap.o \
	PersistentTrapFactory.o \
	Reservoir.o \
	Trap.o \
	generics.o \
	main.o \
	utils.o


TAR = /apps/oss/bin/tar
MAKEDEPEND = /usr/bin/makedepend

ML = tracktraps

SERIAL_DATA_ACCESS_INC = $(LIBDIR)/SerialDataAccess/src
SERIAL_DATA_ACCESS_LIB = $(LIBDIR)/lib/$(machine)/libSerialDataAccess.a

DATA_ACCESS_INC = $(LIBDIR)/DataAccess/src
DATA_ACCESS_LIB = $(LIBDIR)/lib/$(machine)/libDataAccess.a

DATABASE_INC	= $(LIBDIR)/TableIO/src
DATABASE_LIB    = $(LIBDIR)/lib/$(machine)/libdatabase.a

CBMGENERICS_INC	= $(LIBDIR)/CBMGenerics/src
CBMGENERICS_LIB	= $(LIBDIR)/lib/$(machine)/libCBMGenerics.a

EOSPACK_INC     = $(LIBDIR)/EosPack/src
EOSPACK_LIB	= $(LIBDIR)/lib/$(machine)/libEosPack.a

UTILITIES_INC	= $(LIBDIR)/utilities/src
UTILITIES_LIB    = $(LIBDIR)/lib/$(machine)/libutilities.a

H5_SERIAL_INC   = $(LIBDIR)/Serial_Hdf5/src
H5_SERIAL_LIB   = $(LIBDIR)/lib/$(machine)/libserialhdf5.a

INCLUDEDIRS = -I$(EOSPACK_INC) \
              -I$(CBMGENERICS_INC) \
              -I$(SERIAL_DATA_ACCESS_INC) \
	      -I$(SERIAL_DATA_ACCESS_INC)/Interface \
              -I$(DATA_ACCESS_INC) \
	      -I$(DATA_ACCESS_INC)/Interface \
              -I$(DATABASE_INC) \
	      -I$(UTILITIES_INC) \
 	      -I$(HDF5_SINCLUDE)

LIB =  \
       $(EOSPACK_LIB) \
       $(DATA_ACCESS_LIB) \
       $(SERIAL_DATA_ACCESS_LIB) \
       $(DATA_ACCESS_LIB) \
       $(DATABASE_LIB) \
       $(H5_SERIAL_LIB) \
       $(CBMGENERICS_LIB) \
       $(UTILITIES_LIB) \
       $(HDF5_SLIB)/libhdf5.a \
       -lz -lm -lrt


SELECTEDLIB = $(LIB)

vpath %.h ${SRCDIR}
vpath %.C ${SRCDIR}

OBJDIR		= .
vpath %.o ${OBJDIR}

target: $(ML)

$(MLOBJECTS):

CXXFLAGS += $(INCLUDEDIRS)

$(ML) : $(MLOBJECTS) $(SELECTEDLIB) Makefile
	$(PURIFY) $(LCC) $(CFLAGS) $(MLOBJECTS) $(SELECTEDLIB) $(DLLIB) -o $(ML)

clean:
	rm -rf $(ML) $(MLOBJECTS) \
	core test test.out snap.* ii_files SunWS_cache

DATE = `date +'%y%m%d_%H%M%S'`

release:
	cd ../src && $(TAR) cvhf ../releases/$(DATE).tar *.C *.h Makefile Make.*

depend: $(MLOBJECTS:.o=.C)
	cd ../src && $(MAKEDEPEND) -f ../Makefile.tracktraps -Y $(INCLUDEDIRS) $(MLOBJECTS:.o=.C) 2> /dev/null

# DO NOT DELETE

ProjectHandle.o: ../../../libraries/TableIO/src/database.h
ProjectHandle.o: ../../../libraries/TableIO/src/stdafx.h
ProjectHandle.o: ../../../libraries/TableIO/src/DllExport.h
ProjectHandle.o: ../../../libraries/TableIO/src/dataschema.h
ProjectHandle.o: ../../../libraries/TableIO/src/datatype.h
ProjectHandle.o: ../../../libraries/TableIO/src/cauldronschema.h
ProjectHandle.o: ../../../libraries/TableIO/src/cauldronschemafuncs.h
ProjectHandle.o: ProjectHandle.h
ProjectHandle.o: ../../../libraries/DataAccess/src/Interface/ProjectHandle.h
ProjectHandle.o: ../../../libraries/DataAccess/src/Interface/Interface.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/hdf5.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5public.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5pubconf.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5api_adpt.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Apublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Ipublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5ACpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Bpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Dpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Epublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Fpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Gpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Opublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5HGpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5HLpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5MMpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Ppublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Zpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Rpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Spublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Tpublic.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDcore.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDfamily.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDlog.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpi.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpio.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpiposix.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmulti.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDsec2.h
ProjectHandle.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDstdio.h
ProjectHandle.o: Reservoir.h
ProjectHandle.o: ../../../libraries/DataAccess/src/Interface/Reservoir.h
ProjectHandle.o: ../../../libraries/DataAccess/src/Interface/DAObject.h
ProjectHandle.o: ../../../libraries/DataAccess/src/Interface/Parent.h
ProjectHandle.o: ../../../libraries/DataAccess/src/Interface/DynArray.h
ProjectHandle.o: ../../../libraries/DataAccess/src/Interface/AttributeValue.h
ProjectHandle.o: ../../../libraries/DataAccess/src/Interface/Child.h
ProjectHandle.o: ../../../libraries/DataAccess/src/Interface/Interface.h
ProjectHandle.o: Trap.h generics.h
ProjectHandle.o: ../../../libraries/CBMGenerics/src/ComponentManager.h
ProjectHandle.o: ../../../libraries/CBMGenerics/src/consts.h
ProjectHandle.o: ../../../libraries/DataAccess/src/Interface/Trap.h
ProjectHandle.o: PersistentTrap.h
ProjectHandle.o: ../../../libraries/DataAccess/src/Interface/Snapshot.h
PersistentTrap.o: ../../../libraries/TableIO/src/database.h
PersistentTrap.o: ../../../libraries/TableIO/src/stdafx.h
PersistentTrap.o: ../../../libraries/TableIO/src/DllExport.h
PersistentTrap.o: ../../../libraries/TableIO/src/dataschema.h
PersistentTrap.o: ../../../libraries/TableIO/src/datatype.h
PersistentTrap.o: ../../../libraries/DataAccess/src/Interface/Grid.h
PersistentTrap.o: PersistentTrap.h Trap.h generics.h
PersistentTrap.o: ../../../libraries/CBMGenerics/src/ComponentManager.h
PersistentTrap.o: ../../../libraries/CBMGenerics/src/consts.h
PersistentTrap.o: ../../../libraries/DataAccess/src/Interface/Trap.h
PersistentTrap.o: ../../../libraries/DataAccess/src/Interface/DAObject.h
PersistentTrap.o: ../../../libraries/DataAccess/src/Interface/Parent.h
PersistentTrap.o: ../../../libraries/DataAccess/src/Interface/DynArray.h
PersistentTrap.o: ../../../libraries/DataAccess/src/Interface/AttributeValue.h
PersistentTrap.o: ../../../libraries/DataAccess/src/Interface/Child.h
PersistentTrap.o: ../../../libraries/DataAccess/src/Interface/Interface.h
PersistentTrapFactory.o: ../../../libraries/TableIO/src/database.h
PersistentTrapFactory.o: ../../../libraries/TableIO/src/stdafx.h
PersistentTrapFactory.o: ../../../libraries/TableIO/src/DllExport.h
PersistentTrapFactory.o: ../../../libraries/TableIO/src/dataschema.h
PersistentTrapFactory.o: ../../../libraries/TableIO/src/datatype.h
PersistentTrapFactory.o: ../../../libraries/DataAccess/src/Interface/ObjectFactory.h
PersistentTrapFactory.o: ../../../libraries/DataAccess/src/Interface/Interface.h
PersistentTrapFactory.o: PersistentTrapFactory.h Trap.h generics.h
PersistentTrapFactory.o: ../../../libraries/CBMGenerics/src/ComponentManager.h
PersistentTrapFactory.o: ../../../libraries/CBMGenerics/src/consts.h
PersistentTrapFactory.o: ../../../libraries/DataAccess/src/Interface/Trap.h
PersistentTrapFactory.o: ../../../libraries/DataAccess/src/Interface/DAObject.h
PersistentTrapFactory.o: ../../../libraries/DataAccess/src/Interface/Parent.h
PersistentTrapFactory.o: ../../../libraries/DataAccess/src/Interface/DynArray.h
PersistentTrapFactory.o: ../../../libraries/DataAccess/src/Interface/AttributeValue.h
PersistentTrapFactory.o: ../../../libraries/DataAccess/src/Interface/Child.h
PersistentTrapFactory.o: Reservoir.h
PersistentTrapFactory.o: ../../../libraries/DataAccess/src/Interface/Reservoir.h
PersistentTrapFactory.o: ProjectHandle.h
PersistentTrapFactory.o: ../../../libraries/DataAccess/src/Interface/ProjectHandle.h
PersistentTrapFactory.o: ../../../libraries/DataAccess/src/Interface/Interface.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/hdf5.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5public.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5pubconf.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5api_adpt.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Apublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Ipublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5ACpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Bpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Dpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Epublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Fpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Gpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Opublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5HGpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5HLpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5MMpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Ppublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Zpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Rpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Spublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Tpublic.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDcore.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDfamily.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDlog.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpi.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpio.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpiposix.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmulti.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDsec2.h
PersistentTrapFactory.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDstdio.h
Reservoir.o: ../../../libraries/TableIO/src/database.h
Reservoir.o: ../../../libraries/TableIO/src/stdafx.h
Reservoir.o: ../../../libraries/TableIO/src/DllExport.h
Reservoir.o: ../../../libraries/TableIO/src/dataschema.h
Reservoir.o: ../../../libraries/TableIO/src/datatype.h
Reservoir.o: ../../../libraries/TableIO/src/cauldronschema.h
Reservoir.o: ../../../libraries/TableIO/src/cauldronschemafuncs.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/ProjectHandle.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/Interface.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/hdf5.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5public.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5pubconf.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5api_adpt.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Apublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Ipublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5ACpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Bpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Dpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Epublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Fpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Gpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Opublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5HGpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5HLpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5MMpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Ppublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Zpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Rpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Spublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Tpublic.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDcore.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDfamily.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDlog.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpi.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpio.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpiposix.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmulti.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDsec2.h
Reservoir.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDstdio.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/PropertyValue.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/DAObject.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/Parent.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/DynArray.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/AttributeValue.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/Child.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/Interface.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/Formation.h
Reservoir.o: ../../../libraries/CBMGenerics/src/capillarySealStrength.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/Surface.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/Snapshot.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/GridMap.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/Grid.h Reservoir.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/Reservoir.h Trap.h
Reservoir.o: generics.h ../../../libraries/CBMGenerics/src/ComponentManager.h
Reservoir.o: ../../../libraries/CBMGenerics/src/consts.h
Reservoir.o: ../../../libraries/DataAccess/src/Interface/Trap.h
Reservoir.o: PersistentTrap.h
Trap.o: Trap.h generics.h
Trap.o: ../../../libraries/CBMGenerics/src/ComponentManager.h
Trap.o: ../../../libraries/TableIO/src/DllExport.h
Trap.o: ../../../libraries/CBMGenerics/src/consts.h
Trap.o: ../../../libraries/DataAccess/src/Interface/Trap.h
Trap.o: ../../../libraries/DataAccess/src/Interface/DAObject.h
Trap.o: ../../../libraries/DataAccess/src/Interface/Parent.h
Trap.o: ../../../libraries/DataAccess/src/Interface/DynArray.h
Trap.o: ../../../libraries/DataAccess/src/Interface/AttributeValue.h
Trap.o: ../../../libraries/DataAccess/src/Interface/Child.h
Trap.o: ../../../libraries/DataAccess/src/Interface/Interface.h
Trap.o: PersistentTrap.h Reservoir.h
Trap.o: ../../../libraries/DataAccess/src/Interface/Reservoir.h
Trap.o: ../../../libraries/DataAccess/src/Interface/Snapshot.h
Trap.o: ../../../libraries/TableIO/src/database.h
Trap.o: ../../../libraries/TableIO/src/stdafx.h
Trap.o: ../../../libraries/TableIO/src/dataschema.h
Trap.o: ../../../libraries/TableIO/src/datatype.h
Trap.o: ../../../libraries/TableIO/src/cauldronschemafuncs.h
Trap.o: ../../../libraries/EosPack/src/EosPack.h
Trap.o: ../../../libraries/EosPack/src/polynomials.h
generics.o: generics.h ../../../libraries/CBMGenerics/src/ComponentManager.h
generics.o: ../../../libraries/TableIO/src/DllExport.h
generics.o: ../../../libraries/CBMGenerics/src/consts.h
main.o: PersistentTrapFactory.h
main.o: ../../../libraries/DataAccess/src/Interface/ObjectFactory.h
main.o: ../../../libraries/DataAccess/src/Interface/Interface.h
main.o: ProjectHandle.h
main.o: ../../../libraries/DataAccess/src/Interface/ProjectHandle.h
main.o: ../../../libraries/DataAccess/src/Interface/Interface.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/hdf5.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5public.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5pubconf.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5api_adpt.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Apublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Ipublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5ACpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Bpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Dpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Epublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Fpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Gpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Opublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5HGpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5HLpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5MMpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Ppublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Zpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Rpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Spublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Tpublic.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDcore.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDfamily.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDlog.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpi.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpio.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpiposix.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmulti.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDsec2.h
main.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDstdio.h
main.o: ../../../libraries/TableIO/src/database.h
main.o: ../../../libraries/TableIO/src/stdafx.h
main.o: ../../../libraries/TableIO/src/DllExport.h
main.o: ../../../libraries/TableIO/src/dataschema.h
main.o: ../../../libraries/TableIO/src/datatype.h utils.h
utils.o: utils.h ../../../libraries/DataAccess/src/Interface/ProjectHandle.h
utils.o: ../../../libraries/DataAccess/src/Interface/Interface.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/hdf5.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5public.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5pubconf.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5api_adpt.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Apublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Ipublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5ACpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Bpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Dpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Epublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Fpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Gpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Opublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5HGpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5HLpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5MMpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Ppublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Zpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Rpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Spublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5Tpublic.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDcore.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDfamily.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDlog.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpi.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpio.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmpiposix.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDmulti.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDsec2.h
utils.o: /nfs/rvl/groups/ept-sg/SWEast/Cauldron/hpc/hdf5-intel/1.6.8/LinuxRHEL64_x86_64_53WS/include/H5FDstdio.h
utils.o: ../../../libraries/TableIO/src/database.h
utils.o: ../../../libraries/TableIO/src/stdafx.h
utils.o: ../../../libraries/TableIO/src/DllExport.h
utils.o: ../../../libraries/TableIO/src/dataschema.h
utils.o: ../../../libraries/TableIO/src/datatype.h
utils.o: ../../../libraries/TableIO/src/cauldronschema.h
utils.o: ../../../libraries/TableIO/src/cauldronschemafuncs.h
