#!/bin/csh

set verbose

########################## fastmig tests ######################################

cd /nfs/rvl/groups/ept-sg/SWEast/Cauldron/RegressionTests

/bin/rm -rf fastmig
/bin/rm -rf fastmig

mkdir -p fastmig
cd fastmig

fastretrieve fastmig Acquifer
fastconducttest -application fastmig -project  Acquifer -platform Linux64 -cluster $cluster -procs 1 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  Acquifer -platform Linux64 -cluster $cluster -procs 2 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  Acquifer -platform Linux64 -cluster $cluster -procs 4 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  Acquifer -platform Linux64 -cluster $cluster -procs 8 -testdir $testdir &
sleep $sleeptime

fastretrieve fastmig AcquiferWithSandySeal
fastconducttest -application fastmig -project  AcquiferWithSandySeal -platform Linux64 -cluster $cluster -procs 1 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  AcquiferWithSandySeal -platform Linux64 -cluster $cluster -procs 6 -testdir $testdir &
sleep $sleeptime

fastretrieve fastmig China
fastconducttest -application fastmig -project  China -platform Linux64 -cluster $cluster -procs 1 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  China -platform Linux64 -cluster $cluster -procs 4 -testdir $testdir &
sleep $sleeptime

fastretrieve fastmig Tutorial
fastconducttest -application fastmig -project  Tutorial -platform Linux64 -cluster $cluster -procs 1 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  Tutorial -platform Linux64 -cluster $cluster -procs 5 -testdir $testdir &
sleep $sleeptime

fastretrieve fastmig OrphanBasin
fastconducttest -application fastmig -project  OrphanBasin -platform Linux64 -cluster $cluster -procs 1 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  OrphanBasin -platform Linux64 -cluster $cluster -procs 2 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  OrphanBasin -platform Linux64 -cluster $cluster -procs 3 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  OrphanBasin -platform Linux64 -cluster $cluster -procs 7 -testdir $testdir &
sleep $sleeptime

fastretrieve fastmig AcquiferWithGas
fastconducttest -application fastmig -project  AcquiferWithGas -platform Linux64 -cluster $cluster -procs 1 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  AcquiferWithGas -platform Linux64 -cluster $cluster -procs 4 -testdir $testdir &
sleep $sleeptime

fastretrieve fastmig Groningen
fastconducttest -application fastmig -project  Groningen -platform Linux64 -cluster $cluster -procs 1 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  Groningen -platform Linux64 -cluster $cluster -procs 4 -testdir $testdir &
sleep $sleeptime

fastretrieve fastmig Marmul
fastconducttest -application fastmig -project  Marmul -platform Linux64 -cluster $cluster -procs 1 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  Marmul -platform Linux64 -cluster $cluster -procs 4 -testdir $testdir &
sleep $sleeptime

fastretrieve fastmig PL_Spinel
fastconducttest -application fastmig -project  PL_Spinel -platform Linux64 -cluster $cluster -procs 3 -testdir $testdir &
sleep $sleeptime

fastretrieve fastmig Perdido_2005
fastconducttest -application fastmig -project  Perdido_2005 -platform Linux64 -cluster $cluster -procs 4 -testdir $testdir &
sleep $sleeptime

fastretrieve fastmig Acquifer2007_12_TypeI_OTGC_ON
fastconducttest -application fastmig -project  Acquifer2007_12_TypeI_OTGC_ON -platform Linux64 -cluster $cluster -procs 1 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  Acquifer2007_12_TypeI_OTGC_ON -platform Linux64 -cluster $cluster -procs 2 -testdir $testdir &
sleep $sleeptime
fastconducttest -application fastmig -project  Acquifer2007_12_TypeI_OTGC_ON -platform Linux64 -cluster $cluster -procs 4 -testdir $testdir &

