#!/bin/sh

# setting variables
PATH=/glb/home/ksaho3/Eclipse/TF/TEE-CLC-11.0.0:$PATH

WORKSPACE=RegressionTestBench
COLLECTION=https://tfs.sede-coe.pds.nl/tfs/COE-II
ROOTDIRECTORY=/glb/home/`whoami`/RegressionTestBench

# Creating and mapping the workspace
if tf workspaces -collection:${COLLECTION} | grep -q ^${WORKSPACE} ; then
    echo "- deleting existing workspace $WORKSPACE"
    tf workspace -noprompt -delete -collection:$COLLECTION $WORKSPACE
fi
echo "- Creating new workspace $WORKSPACE"
tf workspace -noprompt -new -collection:$COLLECTION $WORKSPACE -comment:"RegressionTestBench"
echo "- Mapping workspace $WORKSPACE to folder $ROOTDIRECTORY"
tf workfold  -noprompt -map -collection:$COLLECTION -workspace:$WORKSPACE \$/Basin\ Modeling/Tests/RegressionTestBench $ROOTDIRECTORY

# creating directory to hold the scripts
echo "- (Re-)creating work folder $ROOTDIRECTORY"
rm -rf $ROOTDIRECTORY
mkdir -p $ROOTDIRECTORY
cd $ROOTDIRECTORY

echo "`pwd` - Retrieving regression test bench ..."
tf get -recursive -force "$ROOTDIRECTORY"

./fastperformtests $*

chmod -R g+w $testbenchpath
chgrp -R g_psaz00 $testbenchpath
