#!/bin/csh -l
#
# calls the script to build all applications
#
# Syntax: $0 <number_of_bits>
#
# Notes:
# 1. This script also update the location where the script will be called
# 2. This script must be csh so we can call gocbm
################################################################################

# define my home location
setenv REGRESSION_HOME       /nfs/rvl/groups/ept-sg/SWEast/Cauldron/Regression
#setenv REGRESSION_SCRIPTS    $REGRESSION_HOME/scripts
setenv REGRESSION_SCRIPTS    `pwd`

# get the number of bits of the target platform
set bits = $1
if ( ${?bits} == 0 ) then
    setenv bits 64
endif

# setup the development environment
source ~ibs/bin/gocbm $bits >> /dev/null

# now call the korn shell scripts that will do the rest
$REGRESSION_SCRIPTS/RegressionTests $bits 

# now get out of here
exit 0


setenv PROJECTNAMES "( \
    Acquifer \
    AreaC \
)"

setenv PROJECTNAMES "( \
    Acquifer \
    AreaC \
    Bonaparte \
    Borneo \
    GOM \
    Gabon \
    GreenRiver \
    Groningen \
    L02 \
    Marmul \
    NAM \
    NVG \
    Nigeria \
    Oman \
    Perdido \
    SNS \
    Saudi \
    SharkDipLine \
    Trinidad \
    Tutorial \
    WNB \
)"

cd $CBMTESTSDIR
svn update

${CBMSCRIPTSDIR}/subscale.pl ${CBMSCRIPTSDIR}/projectScalings.dat

${CBMSCRIPTSDIR}/runVersion $CBMBUILDSDIR/trunk genex alfred.vanderhoeven
${CBMSCRIPTSDIR}/runVersion ${CBMBUILDSDIR}/branches/alfred genex alfred.vanderhoeven
${CBMSCRIPTSDIR}/runVersion ${CBMBUILDSDIR}/branches/olivier genex olivier.meuric

$CBMSCRIPTSDIR/compareVersions trunk alfred genex alfred.vanderhoeven
$CBMSCRIPTSDIR/compareVersions trunk olivier genex olivier.meuric

${CBMSCRIPTSDIR}/runVersion $CBMBUILDSDIR/trunk newtemperature alfred.vanderhoeven
${CBMSCRIPTSDIR}/runVersion ${CBMBUILDSDIR}/branches/bill newtemperature william.senior

$CBMSCRIPTSDIR/compareVersions trunk bill newtemperature william.senior
