#!/bin/csh -f

# echo "---- executing $0 $*"

set cwd = `pwd`

if ( $#argv != 7 ) then 

    echo "Usage: $0 ExecutableName ExecutablePath CalculationScope ProjectName NumberCPU PostFix EmailName"
    goto done

endif

set executableName   = $1
set executablePath   = $2
set scope            = $3
set projectName      = $4
set numProcessors    = $5
set postfix          = $6
set emailName        = $7
set modelName        = ${projectName}_$postfix

if ( -e ${modelName}_CauldronOutputDir ) rm -fr ${modelName}_CauldronOutputDir

set errorLog = ${CBMTESTLOGSDIR}/log.${modelName}.${scope}.${numProcessors}
set timeLog = ${CBMTESTLOGSDIR}/time.${modelName}.${scope}.${numProcessors}

# cp $projectName.project3d.reference $modelName.project3d

sed 's/v2004.01/v2005.02/' $projectName.project3d > $modelName.project3d

set exitStatus = 0
if ( $executableName == "Cauldron" ) then

    /usr/bin/time -l $executablePath/cauldron -batch -txtprogress -$scope $modelName.project3d > $errorLog
    tail -16 $errorLog >& $timeLog

    echo $modelName : Cauldron Run Executed.

else

    if ( $scope == migration ) then
       /usr/bin/time -l mpirun -np $numProcessors $executablePath/fastcauldron -genex -maps -volumes -project $modelName.project3d >& $errorLog
       tail -16 $errorLog >& $timeLog
       /usr/bin/time -l mpirun -np $numProcessors $executablePath/fastcauldron -hrdecompaction -maps -project $modelName.project3d >>& $errorLog
       tail -16 $errorLog >>& $timeLog

       setenv LD_LIBRARY64_PATH /apps/sss/ibs/v2005.02/IRIX64_6517/geocase64:$LD_LIBRARY64_PATH
       time /apps/sss/ibs/v2005.02/IRIX64_6517/bin/cauldron64 -batch -txtprogress -fastmigration -project $modelName.project3d  >> $errorLog
       tail -16 $errorLog >>& $timeLog
    else
       /usr/bin/time -l mpirun -np $numProcessors $executablePath/fastcauldron -$scope -maps -project $modelName.project3d >& $errorLog
       tail -16 $errorLog >& $timeLog
    endif

   # check for execution failure
   grep "written to"  $errorLog >& /dev/null
   set writeStatus = $status
   grep "PETSC ERROR"  $errorLog >& /dev/null
   set errorStatus = $status

   if ( $writeStatus != 0 || $errorStatus == 0 ) then
      set exitStatus = 1
      echo "${modelName} : Failed"
      echo "    execution log is in $errorLog"
      # mailx -s "Error in nightly run of FastCauldron ($scope) on model $modelName" ${emailName}@shell.com < ${modelName}_${numProcessors}_cpu.log
   else
      echo "${modelName} : Succeeded"
      set exitStatus = 0
   endif
endif

exit $exitStatus
