// Class to read data results from track1d
// The wells are read in the order of sortedIndices,
// this is relevant, because the sorting based on x-value is generated by
// CASA
#pragma once

#include "caseDataCreator.h"

namespace casaWizard
{

namespace sac
{

class SACScenario;
class WellTrajectory;
class WellTrajectoryManager;

class WellTrajectoryDataCreator : public CaseDataCreator
{
public:
  WellTrajectoryDataCreator(SACScenario& scenario, const QString& projectName, const QString& iterationPath);

private:
  struct WellData
  {
    QVector<double> depth;
    QVector<double> value;
  };

  void readCase(const int wellIndex, const int caseIndex);
  WellData readSingleTrajectory(const WellTrajectory& trajectory, const QString& dataFolder, const QString& projectName);

  WellTrajectoryManager& wellTrajectoryManager_;
  QString projectName_;
};

} // namespace sac

} // namespace casaWizard
