#include "../src/cmbAPI.h"
#include "../src/casaAPI.h"
#include "../src/FilePath.h"
#include "../src/FolderPath.h"
#include "../src/PrmSourceRockTOC.h"
#include "../src/PrmTopCrustHeatProduction.h"
#include "../src/RunCase.h"
#include "../src/VarPrmSourceRockTOC.h"
#include "../src/VarPrmTopCrustHeatProduction.h"

#include <memory>
//#include <cmath>

#include <gtest/gtest.h>

using namespace casa;

static const double eps = 1.e-5;

class MutatorTest : public ::testing::Test
{
public:
   MutatorTest( ) : m_minTOC( 5.0 )
             , m_maxTOC( 15.0 )
             , m_minTCHP( 0.1 )
             , m_maxTCHP( 4.9 )
             , m_layerName( "Lower Jurassic" )
             , m_projectFileName( "Ottoland.project3d" )
   { ; }
   ~MutatorTest( ) { ; }

   // set of parameters range for DoE
   const double m_minTOC;
   const double m_maxTOC;

   const double m_minTCHP;
   const double m_maxTCHP;
   
   const char * m_layerName;

   const char * m_projectFileName;
};
  
// Mutator test. There is 1 DoE Tornado experiment with 2 parameters
// Test creates DoE and generates set of project files. Then it loads
// project files back and compares variable parameters value with
// generated by DoE
TEST_F( MutatorTest, Tornado2PrmsMutations )
{
   // create new scenario analysis
   casa::ScenarioAnalysis sc;

   ASSERT_EQ( ErrorHandler::NoError, sc.defineBaseCase( m_projectFileName ) );
   
   // vary 2 parameters
   ASSERT_EQ( ErrorHandler::NoError, BusinessLogicRulesSet::VarySourceRockTOC(          sc, 0, m_layerName, m_minTOC,  m_maxTOC,  VarPrmContinuous::Block ) );
   ASSERT_EQ( ErrorHandler::NoError, BusinessLogicRulesSet::VaryTopCrustHeatProduction( sc, 0,              m_minTCHP, m_maxTCHP, VarPrmContinuous::Block ) );

   // set up and generate DoE
   ASSERT_EQ( ErrorHandler::NoError, sc.setDoEAlgorithm( DoEGenerator::Tornado ) );
   casa::DoEGenerator & doe = sc.doeGenerator( );

   doe.generateDoE( sc.varSpace(), sc.doeCaseSet() );
   
   ASSERT_EQ( 5, sc.doeCaseSet().size() );

   ibs::FolderPath pathToCaseSet = ibs::FolderPath( "." );
   pathToCaseSet << "CaseSet";

   // to prevent failure on the second test run - clean folder
   if ( !pathToCaseSet.empty() ) pathToCaseSet.clean();
   ASSERT_EQ( ErrorHandler::NoError, sc.setScenarioLocation( pathToCaseSet.path().c_str() ) );

   ASSERT_EQ( ErrorHandler::NoError, sc.applyMutations( sc.doeCaseSet() ) );

   pathToCaseSet << "Iteration_1";
   for ( size_t i = 0; i < sc.doeCaseSet().size(); ++i )
   {
      ibs::FilePath casePath( pathToCaseSet.path() );
      casePath << (std::string( "Case_" ) + ibs::to_string( i + 1 ) ) << m_projectFileName;

      // check that all files were generated correctly
      ASSERT_TRUE( casePath.exists() );

      // get parameters from project file
      mbapi::Model caseModel;
      caseModel.loadModelFromProjectFile( casePath.cpath() );

      PrmTopCrustHeatProduction prm_tchp( caseModel );
      PrmSourceRockTOC          prm_toc(  caseModel, m_layerName );

      // get parameters from case set
      const casa::PrmSourceRockTOC * prm1 = dynamic_cast<casa::PrmSourceRockTOC*>( (sc.doeCaseSet())[ i ]->parameter( 0 ).get() );
      ASSERT_TRUE( prm1 != NULL );

      const casa::PrmTopCrustHeatProduction * prm2 = dynamic_cast<casa::PrmTopCrustHeatProduction*>( (sc.doeCaseSet())[ i ]->parameter( 1 ).get() );
      ASSERT_TRUE( prm2 != NULL );

      ASSERT_NEAR( prm1->value(), prm_toc.value(), eps );
      ASSERT_NEAR( prm2->value(), prm_tchp.value(), eps );
   }
   
   // cleaning files/folders
   pathToCaseSet.clean();  // clean folder ./CaseSet/Iteration_1
   pathToCaseSet.cutLast();       
   pathToCaseSet.remove(); // delete folder ./CaseSet
   
   ASSERT_FALSE( pathToCaseSet.exists() );
}

// Two iterations mutator test. There are 2 DoE - Tornado and BoxBehnken experiments with 2 parameters in the test.
// The other functionality is the same as in Tornado mutator test
TEST_F( MutatorTest, TornadoBB2PrmsMutations )
{
   // create new scenario analysis
   casa::ScenarioAnalysis sc;

   ASSERT_EQ( ErrorHandler::NoError, sc.defineBaseCase( m_projectFileName ) );

   // vary 2 parameters
   ASSERT_EQ( ErrorHandler::NoError, BusinessLogicRulesSet::VarySourceRockTOC( sc, 0, m_layerName, m_minTOC, m_maxTOC, VarPrmContinuous::Block ) );
   ASSERT_EQ( ErrorHandler::NoError, BusinessLogicRulesSet::VaryTopCrustHeatProduction( sc, 0, m_minTCHP, m_maxTCHP, VarPrmContinuous::Block ) );

   // set root folder for the experiments
   ibs::FolderPath pathToCaseSet = ibs::FolderPath( "." );
   pathToCaseSet << "CaseSet";

   // to prevent failure on the second test run - clean folder
   if ( !pathToCaseSet.empty() ) pathToCaseSet.clean();

   // set up and generate first DoE
   ASSERT_EQ( ErrorHandler::NoError, sc.setDoEAlgorithm( DoEGenerator::Tornado ) );
   ASSERT_EQ( ErrorHandler::NoError, sc.doeGenerator().generateDoE( sc.varSpace(), sc.doeCaseSet() ) );

   ASSERT_EQ( 5, sc.doeCaseSet().size() );

   // set up and generate the second DoE
   ASSERT_EQ( ErrorHandler::NoError, sc.setDoEAlgorithm( DoEGenerator::BoxBehnken ) );
   ASSERT_EQ( ErrorHandler::NoError, sc.doeGenerator().generateDoE( sc.varSpace(), sc.doeCaseSet() ) );

   ASSERT_EQ( 9, sc.doeCaseSet().size() ); // Box-Behnken & Tornado have central point in common

   ASSERT_EQ( ErrorHandler::NoError, sc.setScenarioLocation( pathToCaseSet.path().c_str() ) );

   for ( size_t expNum = 0; expNum < sc.doeCaseSet().experimentNames().size(); expNum++ )
   {
      // filter experiment
      sc.doeCaseSet().filterByExperimentName( sc.doeCaseSet().experimentNames()[expNum] );
      ASSERT_EQ( 5, sc.doeCaseSet().size() ); // must be 2 times 5 - Tornado + BoxBehnken

      ASSERT_EQ( ErrorHandler::NoError, sc.applyMutations( sc.doeCaseSet() ) );

      // check the results of mutator
      ibs::FolderPath pathToIter = pathToCaseSet;
      pathToIter << std::string( "Iteration_" ) + ibs::to_string( expNum + 1 ) + "_" + sc.doeCaseSet( ).experimentNames( )[ expNum ];

      for ( size_t i = 0; i < sc.doeCaseSet().size(); ++i )
      {
         ibs::FilePath casePath( pathToIter.path( ) );
         casePath << ( std::string( "Case_" ) + ibs::to_string( i + 1 + expNum * 5 ) ) << m_projectFileName;

         // check that all files were generated correctly
         ASSERT_TRUE( casePath.exists() );

         // get parameters from project file
         mbapi::Model caseModel;
         caseModel.loadModelFromProjectFile( casePath.cpath() );

         PrmTopCrustHeatProduction prm_tchp( caseModel );
         PrmSourceRockTOC          prm_toc(  caseModel, m_layerName );

         // get parameters from case set
         const casa::PrmSourceRockTOC * prm1 = dynamic_cast<casa::PrmSourceRockTOC*>( ( sc.doeCaseSet() )[ i ]->parameter( 0 ).get() );
         ASSERT_TRUE( prm1 != NULL );

         const casa::PrmTopCrustHeatProduction * prm2 = dynamic_cast<casa::PrmTopCrustHeatProduction*>( ( sc.doeCaseSet() )[ i ]->parameter( 1 ).get() );
         ASSERT_TRUE( prm2 != NULL );

         ASSERT_NEAR( prm1->value(), prm_toc.value(), eps );
         ASSERT_NEAR( prm2->value(), prm_tchp.value(), eps );
      }

   }
   // cleaning files/folders
   pathToCaseSet.clean();  // clean folder ./CaseSet
   pathToCaseSet.remove(); // delete folder ./CaseSet
}


